language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "6"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "8"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "10"
    - os: osx
      osx_image: xcode9.2
      node_js: "6"
    - os: osx
      osx_image: xcode9.2
      node_js: "8"
    - os: osx
      osx_image: xcode9.2
      node_js: "10"
